# Python para Análise de Dados - Numpy   

<p> Iremos aprender a trabalhar coma biblioteca Numpy.


# Acessando Dimensões no Array

In [1]:
# Importando o Numpy
import numpy as np

In [2]:
# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

In [3]:
my_array

array([[0.10256587, 0.71057252],
       [0.83786177, 0.85873948],
       [0.51455351, 0.57754873],
       [0.00234705, 0.02621066],
       [0.29218053, 0.84813788],
       [0.93700521, 0.93066393],
       [0.69305361, 0.95425262],
       [0.63738159, 0.4759966 ],
       [0.51330572, 0.99878301],
       [0.55149936, 0.04518819]])

In [4]:
# Imprimindo o primeiro elemento (1 linha)
my_array[0]

array([0.10256587, 0.71057252])

In [5]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.10256586621253794

In [6]:
# Primeiro elemento da coluna 1
my_array[0][1]

0.7105725237678473

In [7]:
# Segundo elemento da coluna 1
my_array[1][1]

0.8587394812202477

In [8]:
# Segundo elemento da coluna escrito com virgula.
# O primeiro valor especifica a linha e o segundo valor especifica a coluna.
my_array[1,1]

0.8587394812202477

In [9]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.71057252, 0.85873948, 0.57754873])

In [10]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([7.10572524, 8.58739481, 5.77548726, 0.26210657, 8.48137875,
       9.30663933, 9.54252623, 4.75996603, 9.98783013, 0.4518819 ])

In [11]:
# Comparação retorna indices
my_array > 0.50

array([[False,  True],
       [ True,  True],
       [ True,  True],
       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True, False],
       [ True,  True],
       [ True, False]])

In [12]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.71057252, 0.83786177, 0.85873948, 0.51455351, 0.57754873,
       0.84813788, 0.93700521, 0.93066393, 0.69305361, 0.95425262,
       0.63738159, 0.51330572, 0.99878301, 0.55149936])

# Carregar Arrays NumPy a partir de arquivos de Texto

In [13]:
import numpy as np

In [14]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt', delimiter=',')

In [15]:
dataset.shape

(6,)

In [16]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [17]:
# carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt', skiprows=1, unpack=True )

In [18]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [19]:
# Array B
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [20]:
# Array C
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [21]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt', skip_header=2, filling_values=0)

In [22]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])